"""
core/models.py — Pydantic data models for the financial identity profile.
Pure data — no API calls, no side effects.
"""
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class IncomeSource(BaseModel):
    description: str = Field(..., description="What the person does to earn")
    frequency: str = Field(..., description="daily / weekly / monthly / seasonal")
    estimated_monthly_inr: int = Field(..., description="Estimated monthly income in INR")


class Asset(BaseModel):
    item: str = Field(..., description="Name of the asset")
    estimated_value_inr: int = Field(..., description="Rough market value in INR")


class FinancialProfile(BaseModel):
    """
    A structured financial identity card generated from a conversational interview.
    No formal documents required as input — only what the person says.
    """
    full_name: str
    age: int
    occupation: str
    years_in_occupation: int

    # Income
    income_sources: list[IncomeSource]
    total_monthly_income_inr: int
    monthly_expenses_inr: int
    monthly_savings_inr: int

    # Assets and liabilities
    assets: list[Asset]
    has_bank_account: bool
    has_aadhaar: bool
    has_mobile_phone: bool

    # Work history
    previous_occupations: list[str]
    skills: list[str]
    references_available: bool

    # Profile metadata
    location_city_or_area: str
    languages_spoken: list[str]

    # Narrative fields (generated by AI)
    summary_paragraph: str = Field(
        ...,
        description="2-sentence plain-English summary of this person's financial situation"
    )
    loan_readiness_note: str = Field(
        ...,
        description="One sentence: what loan amount and type this person is realistically eligible for"
    )

    model_config = ConfigDict(json_schema_extra={
            "example": {
                "full_name": "Meena Devi",
                "age": 34,
                "occupation": "Domestic worker",
                "years_in_occupation": 8,
                "income_sources": [
                    {"description": "Cleaning 3 households", "frequency": "monthly", "estimated_monthly_inr": 9000}
                ],
                "total_monthly_income_inr": 9000,
                "monthly_expenses_inr": 6500,
                "monthly_savings_inr": 2500,
                "assets": [{"item": "Mobile phone", "estimated_value_inr": 4000}],
                "has_bank_account": False,
                "has_aadhaar": True,
                "has_mobile_phone": True,
                "previous_occupations": ["Factory worker"],
                "skills": ["Cleaning", "Cooking", "Child care"],
                "references_available": True,
                "location_city_or_area": "Bangalore, Koramangala",
                "languages_spoken": ["Hindi", "Kannada"],
                "summary_paragraph": "Meena Devi is a domestic worker with 8 years of consistent income serving 3 households in Koramangala. She saves approximately Rs 2,500 per month and has no formal debt history.",
                "loan_readiness_note": "Eligible for PM SVANidhi-style micro-loan up to Rs 10,000 based on income stability and Aadhaar verification."
            }
        })
